### ISSUE TITLE
Multiple accounts linked to user

### ISSUE THREAD

**Issue by ErliReci-lab** [Kevinjil/Jellyfin.Xtream#52] opened 2023-01-07 19:36 UTC
Can you add a feature where the Xtream account can be linked to specific users?

I can modify the code myself but I would like an over view on how I can do that. Even if it is like a "hack" to modify a file manually without any UI it would be amazing.

**Comment by Kevinjil** [comment] 2023-01-11 08:43
This is mostly a duplicate of #41. As for the "hack": this is hard in Jellyfin as media is user-independent and you cannot simply know the user that is running a specific media request in Jellyfin.

**Comment by Kevinjil** [comment] 2024-02-29 19:58
Considered a duplicate of #41

**Closed by Kevinjil** 2024-02-29 19:58 UTC
Labels: feature, blocked
