### ISSUE TITLE
NO SETTINGS V0.6.3.0 (10.9.1)

### ISSUE THREAD

**Issue by ashipaek0** [Kevinjil/Jellyfin.Xtream#103] opened 2024-05-17 06:01 UTC
There's no settings in the latest update in 10.9.1

All I have is the login credentials boxes.

No sign it's working or any channels  channelrefresh
![Screenshot_20240517-065748](https://github.com/Kevinjil/Jellyfin.Xtream/assets/25457085/b363b580-e094-4292-85d6-b18aed967364)

**Comment by Kevinjil** [comment] 2024-05-17 06:12
Duplicate of #99

**Closed by Kevinjil** 2024-05-17 06:12 UTC
