### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by TomGaming109** [Kevinjil/Jellyfin.Xtream#131] opened 2024-10-26 14:57 UTC
Hi, probably not overly requested however feel it would be a nice to have. 

The ability to have multiple IPTV accounts added, I have a few people on my system who would like to watch stuff however after a while only 1 can due to the 1 stream per account limit. 

If this is possible I would be really grateful for it.

**Comment by Kevinjil** [comment] 2024-10-26 16:28
Duplicate of #42

**Closed by Kevinjil** 2024-10-26 16:28 UTC
